Gamification_web/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^', include('home_page.urls')),
    url(r'^home/', include('home_page.urls')),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^profile', include('personal_page.urls')),
    url(r'^settings/', include('settings.urls'))
]

settings/urls.py
from django.contrib import admin
from django.conf.urls import url
from . import views
urlpatterns = [
    url(r'^$', views.index),
    url(r'^/$', views.index),
    url(r'events', views.events),
    url(r'set_event_points', views.set_event_points),
    url(r'delevent', views.delete_event),
    url(r'turn_points_on', views.turn_points_on),
    url(r'turn_points_off', views.turn_points_off),
    url(r'^set_maxPoints', views.set_max_points),
    url(r'levels', views.levels),
    url(r'^set_maxLevel', views.set_max_level),
    url(r'^add_level_option', views.add_level_option),
    url(r'^deloption', views.delete_option),
    url(r'^set_level_amount', views.set_level_amount),
    url(r'^turnoff_level', views.turnoff_level),
    url(r'^turnon_level', views.turnon_level),
    url(r'^badges',views.badges),
    url(r'^addparameter', views.add_parameter),
    url(r'^addbadge', views.add_badge),
    url(r'^delete_badge', views.delete_badge),
    url(r'^turnoff_badge', views.turnoff_badge),
    url(r'^turnon_badge', views.turnon_badge),
    url(r'^delete_parameter', views.delete_parameter)
]

settings/models.py
from django.db import models
from django.contrib.auth.models import User


class LMS(models.Model):
    Name = models.CharField(max_length=100)
    PointsIsOn = models.BooleanField(default=False)
    MaxPoints = models.IntegerField(default=0, blank=True, null=True)
    MaxLevel = models.IntegerField(default=10, blank=True, null=True)
    PointPerLevel = models.IntegerField(default=0, blank=True, null=True)


class LMSUsers(models.Model):
    lms = models.ForeignKey(LMS, on_delete=models.CASCADE)
    user = models.ForeignKey(User, unique=True, on_delete=models.CASCADE)


class LMSEvents(models.Model):
    name = models.CharField(max_length=100)
    lms = models.ForeignKey(LMS, on_delete=models.CASCADE)

    class Meta:
        unique_together = ('lms', 'name')

    def __str__(self):
        return self.name


class EventPoints(models.Model):
    event = models.ForeignKey(LMSEvents, on_delete=models.CASCADE)
    lms = models.ForeignKey(LMS, on_delete=models.CASCADE)
    points = models.IntegerField(default=0)

    class Meta:
        unique_together = ('lms', 'event')


class LevelOptions(models.Model):
    event = models.ForeignKey(LMSEvents, on_delete=models.CASCADE)
    lms = models.ForeignKey(LMS, on_delete=models.CASCADE)
    amount = models.IntegerField(default=0)
    isActive = models.BooleanField(default=True)

    class Meta:
        unique_together = ('lms', 'event')


class Parameters(models.Model):
    name = models.CharField(max_length=50)
    event = models.ForeignKey(LMSEvents, on_delete=models.CASCADE, null=True)
    lms = models.ForeignKey(LMS, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.name


class Badges(models.Model):
    name = models.CharField(max_length=50)
    img = models.CharField(max_length=200)
    parameter = models.ForeignKey(Parameters, on_delete=models.CASCADE)
    comparison_type = models.IntegerField(default=0)
    criterion = models.IntegerField(default=0)
    lms = models.ForeignKey(LMS, on_delete=models.CASCADE)
    isActive = models.BooleanField(default=True)

settings/forms.py
from django import forms
from .models import LMS, LMSEvents, EventPoints


class LMSChangeNameForm(forms.ModelForm):
    class Meta:
        model = LMS
        fields = {'Name'}


class LMSCreateForm(forms.ModelForm):
    class Meta:
        model = LMS
        fields = {'Name', 'PointsIsOn', 'MaxPoints'}


class EventForm(forms.ModelForm):
    class Meta:
        model = LMSEvents
        fields = {'name'}

settings/views.py
from django.db.models import QuerySet
from django.shortcuts import render
from .models import LMS, LMSUsers, LMSEvents, EventPoints, LevelOptions, Parameters, Badges
from .forms import LMSChangeNameForm, LMSCreateForm, EventForm
from django.http import HttpResponseRedirect, HttpResponse


# главная страница настройки компонентов игрофикации
def index(request):

    # проверяем создана ли LMS для пользователя
    try:
        users_lms = LMSUsers.objects.get(user=request.user)
    except LMSUsers.DoesNotExist:
        lmsname = 'не создана'
    else:
        lms = users_lms.lms
        lmsname = lms.Name

    if request.method == 'POST':
        # если не LMS не создана, создаем новую и связывыем ее с пользователем
        if lmsname == 'не создана':
            form = LMSCreateForm(request.POST)
            if form.is_valid():
                lms = form.save()
                lms_user = LMSUsers()
                lms_user.lms = lms
                lms_user.user = request.user
                lms_user.save()
                return HttpResponseRedirect('/settings')
        else:
            # поменяем имя LMS
            form = LMSChangeNameForm(request.POST, instance=lms)
            if form.is_valid():
                form.save()
                return HttpResponseRedirect('/settings')
    else:
        if lmsname == 'не создана':
            form = LMSCreateForm
        else:
            form = LMSChangeNameForm(instance=lms)

    return render(request,'settings/index.html',{'lms':lmsname, 'form': form})


# страница настройки событий
def events(request):
    try:
        users_lms = LMSUsers.objects.get(user=request.user)
    except LMSUsers.DoesNotExist:
        return HttpResponseRedirect('/settings')

    lms = users_lms.lms
    if request.method == 'POST':
        form_create = EventForm(request.POST)
        if form_create.is_valid():
            event = LMSEvents()
            event.name = form_create.cleaned_data['name']
            event.lms = lms
            event.save()
            return HttpResponseRedirect('/settings/events')
    else:
        form_create = EventForm

    if lms.MaxPoints is None:
        max_points = "не задано"
    else:
        max_points = lms.MaxPoints

    events_original = LMSEvents.objects.filter(lms=lms)
    event_list = []
    for event in events_original:
        if lms.PointsIsOn:
            try:
                points = EventPoints.objects.get(event=event, lms=lms)
            except EventPoints.DoesNotExist:
                point = 'задать'
                event_list.append((event, point))
            else:
                point = points.points
                event_list.append((event, point))
        else:
            event_list.append((event,))

    data = {'form': form_create, 'events': event_list, 'pointIsOn': lms.PointsIsOn, 'maxPoints': max_points}
    return render(request, 'settings/lms_events.html', data)


# задаем  количество очков для события
def set_event_points(request):
    try:
        users_lms = LMSUsers.objects.get(user=request.user)
    except LMSUsers.DoesNotExist:
        return HttpResponseRedirect('/settings')
    lms = users_lms.lms

    if request.method == 'POST':
        event_id = request.POST.get('event')
        try:
            event = LMSEvents.objects.get(id=event_id)
        except LMSEvents.DoesNotExist:
            return HttpResponseRedirect('/settings/events')
        else:
            try:
                event_points = EventPoints.objects.get(event=event, lms=lms)
            except EventPoints.DoesNotExist:
                event_points = EventPoints()
                event_points.lms = lms
                event_points.event = event
                event_points.points = request.POST.get('points')
                event_points.save()
            else:
                event_points.points = request.POST.get('points')
                event_points.save()
            return HttpResponseRedirect('/settings/events')


def delete_event(request):
    if request.method == 'POST':
        id = request.POST.get('id')
        event = LMSEvents.objects.get(id = id)
        event.delete()
        return HttpResponse('ok', content_type='text/html')


def turn_points_on(request):
    if request.method == 'POST':
        try:
            users_lms = LMSUsers.objects.get(user=request.user)
        except LMSUsers.DoesNotExist:
            return HttpResponse('fail', content_type='text/html')
        else:
            lms = users_lms.lms
            lms.PointsIsOn = True
            lms.save()
            return HttpResponse('ok', content_type='text/html')


def turn_points_off(request):
    if request.method == 'POST':
        try:
            users_lms = LMSUsers.objects.get(user=request.user)
        except LMSUsers.DoesNotExist:
            return HttpResponse('fail', content_type='text/html')
        else:
            lms = users_lms.lms
            lms.PointsIsOn = False
            lms.save()
            return HttpResponse('ok', content_type='text/html')


def set_max_points(request):
    if request.method == 'POST':
        try:
            users_lms = LMSUsers.objects.get(user=request.user)
        except LMSUsers.DoesNotExist:
            return HttpResponseRedirect('/settings/events')
        else:
            maxpoints = request.POST.get('maxpoints')
            lms = users_lms.lms
            lms.MaxPoints = maxpoints
            lms.save()
            return HttpResponseRedirect('/settings/events')

def levels(request):
    try:
        users_lms = LMSUsers.objects.get(user=request.user)
    except LMSUsers.DoesNotExist:
        return HttpResponseRedirect('/settings')
    lms = users_lms.lms
    if lms.MaxLevel == None:
        maxLevel = "не задано"
    else:
        maxLevel = lms.MaxLevel
    events = LMSEvents.objects.filter(lms=lms)
    options = LevelOptions.objects.filter(lms=lms)

    return render(request, 'settings/lms_levels.html',{'maxLevel': maxLevel, 'events': events, 'options': options})


def set_max_level(request):
    if request.method == 'POST':
        try:
            users_lms = LMSUsers.objects.get(user=request.user)
        except LMSUsers.DoesNotExist:
            return HttpResponseRedirect('/settings/levels')
        else:
            maxlevel = request.POST.get('maxlevel')
            lms = users_lms.lms
            lms.MaxLevel = maxlevel
            lms.save()
            return HttpResponseRedirect('/settings/levels')

def add_level_option(request):
    if request.method == 'POST':
        try:
            users_lms = LMSUsers.objects.get(user=request.user)
        except LMSUsers.DoesNotExist:
            return HttpResponseRedirect('/settings/levels')
        else:
            eventid = request.POST.get('event')
            try:
                event = LMSEvents.objects.get(id=eventid)
            except LMSEvents.DoesNotExist:
                return HttpResponseRedirect('/settings/levels')
            else:
                amount = request.POST.get('amount')
                if int(amount) != 0 and amount != None:
                    lms = users_lms.lms
                    option = LevelOptions()
                    option.lms = lms
                    option.event = event
                    option.amount = amount
                    option.isActive = True
                    option.save()
                    return HttpResponseRedirect('/settings/levels')


def delete_option(request):
    if request.method == 'POST':
        id = request.POST.get('id')
        option = LevelOptions.objects.get(id = id)
        option.delete()
        return HttpResponse('ok', content_type='text/html')


def set_level_amount(request):
    if request.method == 'POST':
        id = request.POST.get('cur_option')
        try:
            option = LevelOptions.objects.get(id=id)
        except LevelOptions.DoesNotExist:
            return HttpResponseRedirect('/settings/levels')
        else:
            amount = request.POST.get('amountnew')
            if amount == None:
                return HttpResponseRedirect('/settings/levels')
            else:
                option.amount = amount
                option.save()
                return HttpResponseRedirect('/settings/levels')


def turnoff_level(request):
    if request.method == 'POST':
        id = request.POST.get('id')
        option = LevelOptions.objects.get(id = id)
        option.isActive = False
        option.save()
        return HttpResponse('ok', content_type='text/html')


def turnon_level(request):
    if request.method == 'POST':
        id = request.POST.get('id')
        option = LevelOptions.objects.get(id = id)
        option.isActive = True
        option.save()
        return HttpResponse('ok', content_type='text/html')


def badges(request):
    try:
        users_lms = LMSUsers.objects.get(user=request.user)
    except LMSUsers.DoesNotExist:
        return HttpResponseRedirect('/settings')
    else:
        lms = users_lms.lms
        events = LMSEvents.objects.filter(lms=lms)
        parameters = Parameters.objects.filter(lms=lms)
        badgelist = Badges.objects.filter(lms=lms)
        return render(request, 'settings/lms_badges.html',{'events': events, 'parameters': parameters, 'badges': badgelist})

def add_parameter(request):
    if request.method == 'POST':
        try:
            users_lms = LMSUsers.objects.get(user=request.user)
        except LMSUsers.DoesNotExist:
            return HttpResponseRedirect('/settings')
        else:
            lms = users_lms.lms
            eventid = request.POST.get('event')
            try:
                event = LMSEvents.objects.get(id=eventid)
            except LMSEvents.DoesNotExist:
                event = None
            name = request.POST.get('name')
            parameter = Parameters()
            parameter.lms = lms
            parameter.event = event
            parameter.name = name
            parameter.save()
            return HttpResponseRedirect('/settings/badges')

settings/templates/settings/lms_badges.html
{% extends 'settings/index.html' %}
{% load staticfiles %}
{% block head %}
 <style>
    .thumbnails.image_picker_selector  img {
        width: 60px;
        height: 67px;
    }
    @media (min-width: 1200px)
    {
        #cardBadge{
            max-width: 15rem;
        }
    }
 </style>

{% endblock %}
{% block content %}

    <ul class="nav nav-tabs" role="tablist" id="firstTitle">
    <li class="nav-item">
        <a class="nav-link active" data-toggle="tab" href="#badges" role="tab">Бейджи</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" data-toggle="tab" href="#parameters" role="tab">Показатели</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" data-toggle="tab" href="#newbadges" role="tab">Создать</a>
    </li>
    </ul>


    <div class="tab-content mb-5">
        <div class="tab-pane active mt-4" id="badges" role="tabpanel">
        <div class="container-fluid border-top mt-4 mb-3" style="background: repeating-linear-gradient(135deg,transparent,transparent 5px,hsla(0,0%,70%,.03) 0,hsla(0,0%,70%,.03) 10px) hsla(0,0%,70%,.03);">
            <div class="card-deck-wrapper pb-5 pt-5">
            <div class="card-deck">
            {% for badge in badges %}
                {% if badge.isActive %}
                    <div class="card text-center border-dark pt-4" id="cardBadge">
                {% else %}
                    <div class="card text-center text-muted" id="cardBadge">
                {% endif %}
                    <img class="card-img-top p-2 img-fluid" src="{{ badge.img }}" alt="Card image cap">
                    <div class="card-body">
                        <h5 class="card-title">{{ badge.name }}</h5>
                        <p class="card-text">Условие получения: {{ badge.parameter }}
                            {% if badge.comparison_type == 0 %} = {% endif %}
                            {% if badge.comparison_type == 1 %} > {% endif %}
                            {% if badge.comparison_type == 2 %} < {% endif %}
                            {{ badge.criterion }}</p>
                    </div>
                    <div class="card-footer text-center">
                            {% if badge.isActive %}
                                <button id ="{{ badge.id }}" class="btn btn-light fas fa-power-off" onclick="turnoff(this.id);"></button>
                            {% else %}
                                <button id ="{{ badge.id }}" class="btn btn-light fas fa-plug" onclick="turnon(this.id);"></button>
                            {% endif %}
                            <button id ="{{ badge.id }}" class="btn btn-light fas fa-trash" data-toggle="modal" data-target="#badgeDeleteConfirm"></button>
                        </div>
                </div>
            {% endfor %}
        </div>
        </div>
    </div>
        </div>


        <div class="tab-pane" id="parameters" role="tabpanel">

             <form action="/settings/addparameter" method="post" class="col-12 pt-4">
             {% csrf_token %}
                 <div class="form-group row align-items-sm-center">
                     <label class="col-4 col-sm-3 text-muted">Новый показатель</label>
                     <div class="col-8 pl-0 col-sm-3">
                         <input id="id_name" name="name" class="form-control" type="text" required placeholder="Название">
                     </div>
                     <div class="col-12 text-right col-sm-3">
                         <select class="custom-select col-8" id="id_event" name="event">
                             <option value="-1" selected>Выберите событие</option>
                             {% for event in events %}
                                 <option value="{{ event.id }}">{{ event }}</option>
                             {% endfor %}
                         </select>
                     </div>
                     <div class="col-12 col-sm text-right pt-4 pt-sm-0">
                         <button type="submit" class= "btn btn-outline-primary">Добавить</button>
                     </div>
                 </div>
             </form>


                <ul class="list-group col-12">
                    {% for parameter in parameters %}
                        <li class="list-group-item d-flex justify-content-between align-items-center">{{ parameter.name }}
                            <div>
                                <button id ="{{ parameter.id }}" class="btn btn-light fas fa-pencil-alt" data-toggle="modal" data-target="#editParameter{{ parameter.id }}"></button>
                                <button id ="{{ parameter.id }}" class="btn btn-light fas fa-trash" data-toggle="modal" data-target="#parameterDeleteConfirm"></button>
                            </div>
                        </li>
                    {% endfor %}
                </ul>


        </div>

        <div class="tab-pane" id="newbadges" role="tabpanel">
             <form action="/settings/addbadge" method="post" class="col-12 pt-4">
             {% csrf_token %}
                 <div class="form-group row align-items-center">
                     <label for="id_name" class="col-4 col-sm-2 col-form-label text-muted">Название</label>
                     <div class="col-8 col-sm-6">
                         <input id="id_name" name="name" class="form-control" type="text" required>
                     </div>
                 </div>
                 <div class="form-group row align-items-center">
                     <label for="id_parameter" class="col-4 col-sm-2 col-form-label text-muted">Как получить</label>
                         <div class="input-group col-8 col-sm-6">
                             <div class="input-group-append col-12 col-sm-5 p-0">
                             <select class="custom-select col-12" id="id_parameter" name="parameter">
                                 <option selected value="Не выбрано">Выберите...</option>
                                 {% for parameter in parameters %}
                                     <option value="{{ parameter.id }}">{{ parameter }}</option>
                                 {% endfor %}
                             </select>
                             </div>
                            <div class="input-group-append col-12 col-sm-2 pl-sm-1 pl-0 pr-0">
                             <select class="custom-select col-12" id="id_comparison" name="comparison">
                                 <option selected value="0"> = </option>
                                 <option value="1"> > </option>
                                 <option value="2"> < </option>
                             </select>
                             </div>
                             <div class="input-group-append col-12 col-sm-5 pl-sm-1 pl-0 pr-0">
                                 <input type="number" class="form-control" name="criteria" id="id_criteria" placeholder="Количество" required min="0" oninput="validity.valid||(value='');">
                             </div>

                     </div>
                 </div>

                 <div class="form-group row align-items-center">
                     <label for="id_badge" class="col-4 col-sm-2 col-form-label text-muted">Картинка</label>
                     <div class="col col-sm-6">
                         <select class="image_picker_selector" id="id_badge" name="badge">
                             <option data-img-src="{% static 'img/badges/Cup_Badge_Color.png' %}" value = "{% static 'img/badges/Cup_Badge_Color.png' %}" data-img-class="m-0 rounded" width="50px" height="50px">1</option>
                             <option data-img-src="{% static 'img/badges/Growth_Badge_Color.png' %}" value = "{% static 'img/badges/Growth_Badge_Color.png' %}" data-img-class="m-0 rounded">2</option>
                             <option data-img-src="{% static 'img/badges/Idea_Badge_Color.png' %}" value = "{% static 'img/badges/Idea_Badge_Color.png' %}" data-img-class="m-0 rounded">3</option>
                             <option data-img-src="{% static 'img/badges/Like_Badge_Color.png' %}" value = "{% static 'img/badges/Like_Badge_Color.png' %}" data-img-class="m-0 rounded">4</option>
                             <option data-img-src="{% static 'img/badges/Medal_Badge_Color.png' %}" value = "{% static 'img/badges/Medal_Badge_Color.png' %}" data-img-class="m-0 rounded">5</option>
                             <option data-img-src="{% static 'img/badges/Monitor_Badge_Color.png' %}" value = "{% static 'img/badges/Monitor_Badge_Color.png' %}" data-img-class="m-0 rounded">6</option>
                             <option data-img-src="{% static 'img/badges/Star_Badge_Color.png' %}" value = "{% static 'img/badges/Star_Badge_Color.png' %}" data-img-class="m-0 rounded">7</option>
                             <option data-img-src="{% static 'img/badges/Shuttle_Badge_Color.png' %}" value = "{% static 'img/badges/Shuttle_Badge_Color.png'%}" data-img-class="m-0 rounded">8</option>
                         </select>
                     </div>
                 </div>
                 <button type="submit" class= "btn btn-outline-primary">Добавить</button>
             </form>
        </div>
    </div>




{% endblock %}

{% block footer %}

    <div class="modal my-fade" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true" id="badgeDeleteConfirm">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-body text-center">
                    <h5>Вы действительно хотите удалить бэйдж?</h5>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-primary" id="confirmButton" onclick="delete_badge()">Да</button>
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Нет</button>
                </div>
            </div>
        </div>
    </div>

    <div class="modal my-fade" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true" id="parameterDeleteConfirm">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-body text-center">
                    <h5>Вы действительно хотите удалить параметр?</h5>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-primary" id="confirmButton" onclick="delete_parameter()">Да</button>
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Нет</button>
                </div>
            </div>
        </div>
    </div>

    {% for parameter in parameters %}
    <div class="modal my-fade" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true" id="editParameter{{ parameter.id }}">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5>Изменение параметра</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <form action="/settings/editparameter" method="post">
                    <div class="modal-body">
                        {% csrf_token %}
                        <div class="form-group row">
                            <div class="col-12">
                                <input id="id_name" name="name" class="form-control" type="text" required placeholder="Название" value="{{ parameter.name }}">
                            </div>
                        </div>
                        <div class="form-group row">
                        <div class="col-12">
                            <select class="custom-select" id="id_event" name="event">
                                    {% for event in events %}
                                        {% if event.id == parameter.event.id %}
                                            <option value="{{ event.id }}" selected>{{ event }}</option>
                                        {% else %}
                                            <option value="{{ event.id }}">{{ event }}</option>
                                        {% endif %}
                                    {% endfor %}
                            </select>
                        </div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="submit" class="btn btn-primary">Сохранить</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    {% endfor %}


{% endblock %}





{% block script %}

   <script>

    currentid = -1
    currentpid = -1
    function OnSuccess (data) {
            if(data='ok'){
                location.reload()
            }
            else
                alert('Произошла ошибка')

    }

        function delete_badge() {
            if (currentid != -1) {
                $.post("/settings/delete_badge/", {id: currentid}, OnSuccess)
            }
        }

        function delete_parameter() {
            if (currentpid != -1) {
                $.post("/settings/delete_parameter/", {id: currentpid}, OnSuccess)
            }
        }

        $('#badgeDeleteConfirm').on('show.bs.modal', function (event) {
        button = $(event.relatedTarget);
        currentid = button[0].id
})

    $('#parameterDeleteConfirm').on('show.bs.modal', function (event) {
        button = $(event.relatedTarget);
        currentpid = button[0].id
})

    function turnoff(id) {

       $.post("/settings/turnoff_badge/", {id: id}, OnSuccess)
   }

   function turnon(id) {

       $.post("/settings/turnon_badge/", {id: id}, OnSuccess)
   }


    $("#id_badge").imagepicker()
    $("#id_badgem").imagepicker()
    </script>

{% endblock %}

settings/templates/settings/lms_change_name_form.html
<form action="/settings/" method="post">
    {% csrf_token %}
    <div class="form-group row pt-2 pb-2 border-top align-items-center">
        <label for="id_Name" class="col col-form-label text-muted">Новое имя системы</label>
        <div class="col">
            <input type="text" class="form-control" id="id_Name" required  name="Name">
            {% for error in form.Name.errors %}
                <div class="text-danger text-center">
                    {{ error }}
                </div>
            {% endfor %}
        </div>
        <div class="col text-right">
            <button type="submit" class="btn btn-primary">Сохранить</button>
        </div>
    </div>
</form>

settings/templates/settings/lms_create_form.html
<form action="/settings/" method="post">
    {% csrf_token %}
    <div class="form-group row pt-2 pb-2 border-top">
        <label for="id_Name" class="col col-form-label text-muted">Имя системы</label>
        <div class="col">
            <input type="text" class="form-control" id="id_Name" required  name="Name">
            {% for error in form.Name.errors %}
                <div class="text-danger text-center">
                    {{ error }}
                </div>
            {% endfor %}
        </div>
    </div>
    <div class="form-group row text-left align-items-center">
        <label for="id_PointsIsOn" class="form-check-label text-muted col">Вести подсчет очков</label>
        <input type="checkbox" class="form-check ml-3" id="id_PointsIsOn" name="PointsIsOn" onclick="hide(this)">
        <div class="col" id ='maxGroup' style="display: none">
            <input type="number" class="form-control" id="id_MaxPoints" name="MaxPoints" placeholder="Максимальное количество очков">
            {% for error in form.MaxPoints.errors %}
                <div class="text-danger text-center">
                    {{ error }}
                </div>
            {% endfor %}
        </div>
        <div class="col text-right">
            <button type="submit" class="btn btn-primary">Создать</button>
        </div>
    </div>
</form>

<script>
    function hide(element) {

        if(element.checked) {
            el = document.getElementById('maxGroup');
            el.style.display = 'flex';
        }
        else {
            el = document.getElementById('maxGroup');
            el.style.display = 'none';
        }
    }

</script>